services:
  service1:
    build:
      context: ./service1
    volumes:
      - ./service1:/service1
      - ./shared_logs:/service1/logs  
    working_dir: /service1
    command: python test1.py

  service2:
    build:
      context: ./service2
    volumes:
      - ./service2:/service2
      - ./shared_logs:/service2/logs  
    working_dir: /service2
    command: python test2.py