from pydantic import BaseModel
# Pydantic models for request and response validation
# Pydantic models for request and response validation
class Employee(BaseModel):
    employee_id: int  # Auto-generated by DB, so no need to provide it on create
    first_name: str
    last_name: str
    email: str
    salary: int

    class Config:
        orm_mode = True  # This allows the Pydantic model to work with SQLAlchemy models

class EmployeeCreate(BaseModel):
    first_name: str
    last_name: str
    email: str
    salary: int
