services:

  

 notebook:
    container_name: jupyter_notebook
    build: ./notebook
    ports:
      - 8888:8888
    volumes:
        - ./notebook:/notebook  # Mount the notebook directory
    # depends_on: #! Make sure to uncomment this line if you want to run the notebook after the db is up
    #   db:
    #       condition: service_healthy 
    #   db_setup: 
    #     condition: service_completed_successfully